
os:
  - Visual Studio 2013
  - Visual Studio 2015

install:
  - mkdir deps
  - cd deps
  # zlib
  - curl -fsSL -o zlib.tar.gz https://github.com/madler/zlib/archive/v1.2.8.tar.gz
  - 7z x zlib.tar.gz -so | 7z x -si -ttar > nul
  - move zlib-1.2.8 zlib
  - cd zlib
  - cmake .
  - cmake --build .
  - cd ..
  # libPNG
  - curl -fsSL -o libpng.tar.gz http://prdownloads.sourceforge.net/libpng/libpng-1.6.28.tar.gz?download
  - 7z x libpng.tar.gz -so | 7z x -si -ttar > nul
  - move libpng-1.6.28 libpng
  - cd libpng
  - cmake . -DZLIB_INCLUDE_DIR=..\zlib -DZLIB_LIBRARY=..\zlib\debug\zlibstaticd.lib
  - cmake --build .
  - cd ..
  # go back to source root
  - cd ..


build_script:
  - mkdir build
  - cd build 
  - cmake .. -DZLIB_INCLUDE_DIR=..\deps\zlib -DZLIB_LIBRARY=..\deps\zlib\debug\zlibstaticd.lib -DPNG_PNG_INCLUDE_DIR=..\deps\libpng -DPNG_LIBRARY=..\deps\libpng\debug\libpng16_staticd.lib
  - cmake --build .
  - ctest -C Debug --output-on-failure
